import {
  Badge,
  Button,
  DomainEntityList,
  DomainModulePage,
  KPICard,
  type DataTableColumn
} from '@insuros/ui';
import { AuditEventService, AuditService } from '@insuros/services';

export const metadata = { title: 'Audit' };

const auditService = new AuditService();
const auditEventService = new AuditEventService();

export default async function AuditCenterPage() {
  const records = await auditService.getAuditRecords();
  const events = await auditEventService.getAuditEvents();

  type AuditRow = (typeof records)[number];
  type AuditEventRow = (typeof events)[number];

  const columns: DataTableColumn<AuditRow>[] = [
    { key: 'entityReference', header: 'Reference' },
    { key: 'module', header: 'Module' },
    { key: 'action', header: 'Action' },
    { key: 'actor', header: 'Actor' },
    { key: 'timestamp', header: 'Timestamp' },
    { key: 'details', header: 'Details' },
    {
      key: 'action',
      header: 'Event',
      render: (row) => (
        <Badge
          tone={
            row.action === 'Approve'
              ? 'success'
              : row.action === 'Reject' || row.action === 'Delete'
                ? 'danger'
                : 'neutral'
          }
        >
          {row.action}
        </Badge>
      )
    }
  ];

  const eventColumns: DataTableColumn<AuditEventRow>[] = [
    { key: 'entityType', header: 'Entity Type' },
    { key: 'entityId', header: 'Entity ID' },
    { key: 'action', header: 'Action' },
    { key: 'actor', header: 'Actor' },
    { key: 'occurredAt', header: 'Occurred At' },
    { key: 'details', header: 'Details' }
  ];

  return (
    <DomainModulePage
      title='Audit Center'
      description='Review immutable audit records and platform audit events for compliance, traceability, and operational governance.'
    >
      <div className='mb-6 grid gap-4 md:grid-cols-3'>
        <KPICard title='Audit Records' value={String(records.length)} change='Tracked records' />
        <KPICard title='Audit Events' value={String(events.length)} change='Platform events' />
        <KPICard title='Approvals' value={String(records.filter((record) => record.action === 'Approve').length)} change='Governed decisions' />
      </div>

      <div className='space-y-6'>
        <DomainEntityList
          title='Audit Events'
          description='Platform-level events generated by workflow, claims, policies, finance, identity, and marketplace operations.'
          searchPlaceholder='Search audit events...'
          columns={eventColumns}
          data={events}
          emptyTitle='No audit events'
          emptyDescription='No platform audit events have been generated yet.'
          emptyAction={<Button>Export Audit Events</Button>}
        />

        <DomainEntityList
          title='Audit Log'
          description='Immutable platform audit records across claims, policies, finance, operations, and identity.'
          searchPlaceholder='Search audit records...'
          columns={columns}
          data={records}
          emptyTitle='No audit records'
          emptyDescription='No audit records have been generated yet.'
          emptyAction={<Button>Export Audit Log</Button>}
        />
      </div>
    </DomainModulePage>
  );
}
